spring:
  application:
    name: eureka-server
  profiles:
    active: dev

# Caso o servidor de configuracao esteja OFF, a configuracao abaixo eh aplicada
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
